package org.wrs.view.dialog;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.event.ActionListener;

/**
 *
 * @author C.Mateo
 */
public class ConfirmUserPasswordDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form ConfirmUserPasswordDialog
     */
    public ConfirmUserPasswordDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        init();
    }
    
    public void setActionListener(ActionListener actionListener) {
        updateUserBtn.addActionListener(actionListener);
    }
    
    private void init(){
        passwordTxt.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;"
                + "showCapsLock:true");
        passwordTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "ingrese la contraseña");

    }
    
    public String getPassword(){
        String currentPassword = new String(passwordTxt.getPassword());
        passwordTxt.setText("");
        return currentPassword;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateUserBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONFIRME SU CONTRASEÑA");

        updateUserBtn.setText("Confirmar");
        updateUserBtn.setActionCommand("updateUserCmd");

        jButton2.setText("Cancelar");
        jButton2.setActionCommand("updateUserCmd");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateUserBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(passwordTxt))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateUserBtn)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton updateUserBtn;
    // End of variables declaration//GEN-END:variables

    
}
